// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wghbnogmnxvsxunvirky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnaGJub2dtbnh2c3h1bnZpcmt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NzczODMsImV4cCI6MjA2OTE1MzM4M30.5GOzSfrykRf-6xnnjEhVtiPqjqtY-_c9Txx8v_sYijA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);